apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jj-anyasi/microservices-gitop.git
    targetRevision: main
    path: charts/backend
    helm:
      releaseName: backend
  destination:
    server: https://kubernetes.default.svc
    # No namespace â†’ everything goes to 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true